name: CI

on: [push, pull_request]

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-ruby@v1
    with:
      ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
  - run: bundle exec rspec